---
# File: site.yml - Example Vault server playbook (Filesystem storage)

- name: Install Vault Vagrant Development Server
  hosts: vault_instances
  any_errors_fatal: true
  become: true
  become_user: root
  tasks:
    - name: Execute Role
      import_role:
        name: /home/jasoet/Documents/Ansible/ansible-vault
        tasks_from: provision
      vars:
        vault_backend: gcs
        vault_install_remotely: false
